//if error occur or not , finally will work



/////error, try, catch, throw 


try{
    console.log(eval("%12+3+6*7"));
}

catch(error){
    console.log(eval("%12+3+6*7"));
}
finally{
console.log("fetch call");
console.log("database commit");
}



